//
//  main.m
//  Assignment 1 - BMI Calculator
//
//  Created by Xinchao Liu on 2/19/13.
//  Copyright (c) 2013 Xinchao Liu. All rights reserved.
//
//  Email: leo_liu@csu.fullerton.edu
//
//  Due: 23:59, Feb.26, 2013
//
//  File Description: Generated by XCode and not been modified.

#import <UIKit/UIKit.h>

#import "AppDelegate.h"

int main(int argc, char *argv[])
{
    @autoreleasepool {
        return UIApplicationMain(argc, argv, nil, NSStringFromClass([AppDelegate class]));
    }
}
